### ISSUE TITLE
"processor null properties" for step with Catalog 4.4.x

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1381]
### Describe the Bug

there should not "null" mentioned

![image](https://github.com/user-attachments/assets/d52a936f-19d7-488b-b44e-5a0593be59cd)

### Steps to Reproduce the Bug or Issue

1. add a "step" component
2. select it
3. click on All in the config panel

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
I cannot reproduce it in VSCode nor in the online version

![Image](https://github.com/user-attachments/assets/ebfa788d-a87c-49e9-9baf-fec9f24e612c)

 ![Image](https://github.com/user-attachments/assets/cdb9da94-ed8f-4d08-b2b8-7f6e2143c3f0)

**Comment by apupier** [comment]
I reproduce when using the Camel Main 4.4.0 or 4.4.0.redhat-00025 catalog.

it is working with Camel Main 4.6.0, 4.7.0 and 4.8.0

**Comment by lordrip** [comment]
Ok, I see it now, this happens because in the past, the group information was under `label` for EIPs, and that changed since a few versions back

* [Camel 4.4.0](https://github.com/apache/camel/blob/f190012b4f2a7fa2720d6da256ccba1d1fb3b091/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/log.json#L21-L22)
* [Camel 4.8.0](https://github.com/apache/camel/blob/e777c141544dabbab09aff57864cfbe8315ae831/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/log.json#L21-L22)
