### ISSUE TITLE
Editing a expression language does not show input box to type the actual expression

### ISSUE THREAD

**Issue by davsclaus** [KaotoIO/kaoto#1443]
### Describe the Bug

For example add `when` to a `choice` and in the dropdown select a language such as simple or groovy. The input text to type the code is not show because "required" button is selected (it should also show this input field. You can work around by turning off "required".

### Steps to Reproduce the Bug or Issue

See below

### Screenshots or Videos

<img width="1912" alt="Screenshot 2024-09-17 at 13 36 21" src="https://github.com/user-attachments/assets/155fb0b8-b602-4680-9002-7ebc7b03953f">

### Platform

Using online
https://kaotoio.github.io/kaoto/#/

**Comment by lordrip** [comment]
This seems to be happening because for EIPs, the form is created out of the JSON Schema, and since simple has many variations, the expression field that we use is not required :cry:.

Context: we need to check if we can cross the JSON Schema and the catalog so we can make the option as required in the form as well.

**Comment by davsclaus** [comment]
the expression field would be required for all of them, you need to type something
